import type { Answer } from './types';

const D = '2026-09-10';

export const ANSWERS: Answer[] = [
  // ---------- process ----------
  {
    id: 'process-registration-office',
    question: 'How does a registration at your offices work?',
    body: 'You book a date and time with us, and on the day the two of you and your two witnesses come to our office. We check your documents, you sign the register, and you are legally married from that moment. We then lodge the marriage with Home Affairs on your behalf, and your certificate follows from them.',
    section: 'process', order: 10,
    appliesTo: { services: ['registration'] },
    triggers: ['office', 'offices', 'come to you'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'process-ceremony',
    question: 'How does the legal part of a ceremony work?',
    body: 'Your officiant meets you beforehand to plan the ceremony with you, so it sounds like you and not like a form. On the day the ceremony includes the legal words and the signing of the register with your two witnesses, so you are married in front of the people you love with nothing left to do afterwards. We then lodge the marriage with Home Affairs and your certificate follows from them.',
    section: 'process', order: 10,
    appliesTo: { services: ['small_ceremony', 'wedding_ceremony'] },
    triggers: ['vows', 'ceremony', 'officiant'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'process-one-non-sa',
    question: 'One of us is not South African. What is different?',
    body: 'When one partner is not a South African citizen, Home Affairs requires a short interview with both of you before the marriage can be registered. We arrange the interview, tell you exactly what to bring, and come with you. It adds a little time to the process, so if you have a date in mind it helps to start early.',
    section: 'process', order: 20,
    appliesTo: { nationalities: ['one_non_sa'] },
    triggers: ['interview', 'immigration', 'visa', 'foreign', 'passport'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'process-permanent-resident',
    question: 'My partner is a permanent resident with an SA ID. Do we still need the interview?',
    body: 'A permanent resident who holds a South African ID is treated like a citizen for the purposes of the marriage, so the interview is not required and the process is the same as for two South Africans.',
    section: 'process', order: 21,
    appliesTo: { nationalities: ['one_non_sa'], nonSaStatuses: ['permanent_resident'] },
    triggers: ['permanent resident', 'pr', 'sa id'],
    status: 'draft', lastReviewed: D,
  },

  // ---------- price ----------
  {
    id: 'price-registration-office',
    question: 'What does a registration at your offices cost, and what is included?',
    body: 'A registration at our offices is {{price:registration_office}}. That covers the appointment, the checking of your documents, the signing, the lodging of your marriage with Home Affairs, and the handwritten certificate you take away on the day. There is nothing to pay at Home Affairs and nothing to pay on the day.',
    section: 'price', order: 10,
    appliesTo: { services: ['registration'] },
    triggers: ['cost', 'price', 'how much', 'fee', 'quote'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'price-registration-home',
    question: 'What does it cost to be registered at home?',
    body: 'If you would rather we come to you, a registration at your home is {{price:registration_home}}, which covers everything a registration at our offices does plus our travel to you within the area we serve.',
    section: 'price', order: 11,
    appliesTo: { services: ['registration'] },
    triggers: ['at home', 'our home', 'come to us', 'travel'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'price-express',
    question: 'Is there a lower-cost option?',
    body: 'Yes. We hold express registration slots on Mondays in Lonehill and Thursdays in Centurion at {{price:registration_express}}. It is the same legal marriage and the same lodging with Home Affairs, in a shorter appointment on a set day.',
    section: 'price', order: 12,
    appliesTo: { provinces: ['gauteng'], services: ['registration'] },
    triggers: ['cheap', 'afford', 'budget', 'express', 'special'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'price-ceremony',
    question: 'What does a ceremony cost?',
    body: 'A small ceremony is {{price:small_ceremony}} and a full wedding ceremony is {{price:wedding_ceremony}}. Both include the planning meeting with your officiant, the ceremony itself written for you, the legal signing, and the lodging of your marriage with Home Affairs.',
    section: 'price', order: 10,
    appliesTo: { services: ['small_ceremony', 'wedding_ceremony'] },
    triggers: ['cost', 'price', 'how much', 'fee', 'quote'],
    status: 'draft', lastReviewed: D,
  },

  // ---------- bring ----------
  {
    id: 'bring-ids',
    question: 'What do we bring on the day?',
    body: 'Each of you brings your original ID (or passport if you are not South African), two copies of it, and two ID photos. Your two witnesses each bring their ID and a copy. That is all.',
    section: 'bring', order: 10,
    appliesTo: {},
    triggers: ['documents', 'bring', 'copies', 'photos', 'id'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'bring-decree',
    question: 'One of us is divorced. What extra do we need?',
    body: 'Bring the final decree of divorce. Home Affairs will not register a new marriage without proof that the previous one has ended, and the decree is that proof. If you cannot find it, tell us early and we will help you get a copy.',
    section: 'bring', order: 20,
    appliesTo: { priorMarriages: ['divorced'] },
    triggers: ['divorce', 'decree', 'divorced', 'previously married'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'bring-death-certificate',
    question: 'One of us is widowed. What extra do we need?',
    body: 'Bring the death certificate of your late spouse. Home Affairs needs it to record that the previous marriage has ended.',
    section: 'bring', order: 20,
    appliesTo: { priorMarriages: ['widowed'] },
    triggers: ['widow', 'widowed', 'late husband', 'late wife', 'death certificate'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'bring-non-sa',
    question: 'What does the non-South African partner bring?',
    body: 'Their passport with a valid visa or permit, and a letter of no impediment from their own country confirming they are free to marry. Some countries call it a certificate of no marriage or a single-status certificate. We will tell you exactly what applies to your partner’s country.',
    section: 'bring', order: 30,
    appliesTo: { nationalities: ['one_non_sa', 'both_non_sa'] },
    triggers: ['no impediment', 'letter', 'passport', 'permit'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'bring-witnesses',
    question: 'Do we need to bring witnesses?',
    body: 'Yes, two adults with their IDs. Friends or family are ideal. If you cannot bring two, tell us when you book and we will arrange witnesses for you.',
    section: 'bring', order: 40,
    appliesTo: {},
    triggers: ['witness', 'witnesses'],
    status: 'draft', lastReviewed: D,
  },

  // ---------- home affairs ----------
  {
    id: 'ha-relationship',
    question: 'What is the difference between you and Home Affairs?',
    body: 'Every marriage in South Africa is registered by Home Affairs, and every marriage officer is appointed by them. What we do is handle the process for you: the appointment on a day that suits you, the checking of your documents so nothing is sent back, the signing, and the lodging with Home Affairs. The certificate itself is issued by Home Affairs either way. You are paying for the process to be done properly, at your convenience, by people who do it every week.',
    section: 'home_affairs', order: 10,
    appliesTo: {},
    triggers: ['home affairs', 'dha', 'free', 'government'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'ha-certificate',
    question: 'How do we get our marriage certificate?',
    body: 'On the day you receive the handwritten certificate from the register. Once Home Affairs has recorded the marriage you can get a printed abridged certificate from any Home Affairs office. If you need an unabridged certificate, which shows both partners’ full details and is what most countries ask for when you apply for a visa, we can obtain it for you for {{price:unabridged_certificate}}.',
    section: 'home_affairs', order: 20,
    appliesTo: {},
    triggers: ['certificate', 'unabridged', 'abridged', 'apostille', 'overseas', 'abroad', 'emigrat'],
    status: 'draft', lastReviewed: D,
  },

  // ---------- specific (only ever pulled in by triggers) ----------
  {
    id: 'specific-saturday',
    question: 'Can we do it on a Saturday?',
    body: 'Yes. We work weekends, at our offices and at your home. Saturdays fill up fastest, so book early.',
    section: 'specific', order: 10,
    appliesTo: {},
    triggers: ['saturday', 'sunday', 'weekend'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'specific-photos',
    question: 'Can we bring a photographer or take photos?',
    body: 'Of course. Bring whoever you like to take photos, at our offices or at your home. Many couples bring a photographer even to a registration.',
    section: 'specific', order: 20,
    appliesTo: {},
    triggers: ['photo', 'photographer', 'pictures'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'specific-surname',
    question: 'Can I change my surname, or keep it?',
    body: 'Either. On the day you tell us which surname you will use: your own, your partner’s, or both joined. It goes into the register and Home Affairs updates your ID from there.',
    section: 'specific', order: 30,
    appliesTo: {},
    triggers: ['surname', 'name change', 'double barrel', 'maiden'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'specific-anc',
    question: 'We want an antenuptial contract. Does that change anything?',
    body: 'An antenuptial contract is signed with a notary before the marriage, and the notary registers it. It does not change what we do, but please tell us you have one so we can note it in the register. Without a contract you are married in community of property.',
    section: 'specific', order: 40,
    appliesTo: {},
    triggers: ['anc', 'antenuptial', 'ante-nuptial', 'community of property', 'accrual', 'contract'],
    status: 'draft', lastReviewed: D,
  },

  // ---------- always ----------
  {
    id: 'always-every-couple',
    question: 'Do you marry same-sex couples?',
    body: 'Yes, and gladly. Every one of our officers is a Civil Union marriage officer, which means we marry every couple. Many officers will not; we always have.',
    section: 'always', order: 10,
    appliesTo: {},
    triggers: ['same sex', 'same-sex', 'gay', 'lesbian', 'civil union'],
    status: 'draft', lastReviewed: D,
  },
  {
    id: 'always-legitimate',
    question: 'How do I know a marriage officer is legitimate?',
    body: 'Every marriage officer is designated by Home Affairs and given a designation number. Ask for it. Ours are on this site, and you can confirm any number by phoning Home Affairs in Pretoria.',
    section: 'always', order: 20,
    appliesTo: {},
    triggers: ['legitimate', 'legit', 'registered officer', 'designation', 'scam'],
    status: 'draft', lastReviewed: D,
  },
];
